# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy only needed project files and .sln first
COPY FOCS.sln ./
COPY FOCS/FOCS.csproj ./FOCS/
COPY FOCS.Common/FOCS.Common.csproj ./FOCS.Common/
COPY FOCS.Infrastructure.Identity/FOCS.Infrastructure.Identity.csproj ./FOCS.Infrastructure.Identity/
COPY FOCS.Application/FOCS.Application.csproj ./FOCS.Application/
COPY FOCS.Order.Infrastucture/FOCS.Order.Infrastucture.csproj ./FOCS.Order.Infrastucture/

# ...add các csproj khác nếu cần

# Restore (sẽ chỉ restore đúng các project reference)
RUN dotnet restore FOCS.sln

# Copy everything else
COPY . .

RUN apt-get update && apt-get install -y libgssapi-krb5-2


# Build the solution
RUN dotnet build FOCS.sln -c Release -o /app/build

# Publish the main API project
RUN dotnet publish ./FOCS/FOCS.csproj -c Release -o /app/publish /p:UseAppHost=false

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "FOCS.dll"]
