# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Keep the build clean
ENV DOTNET_CLI_TELEMETRY_OPTOUT=true
ENV DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true

# Copy only the projects you need (không copy UnitTest)
COPY *.sln . 
COPY FOCS.Application/*.csproj ./FOCS.Application/
COPY FOCS.Common/*.csproj ./FOCS.Common/
COPY FOCS.Infrastructure.Identity/*.csproj ./FOCS.Infrastructure.Identity/
COPY FOCS.Order.Infrastucture/*.csproj ./FOCS.Order.Infrastucture/
COPY FOCS.Realtime.Hub/*.csproj ./FOCS.Realtime.Hub/
COPY FOCS.NotificationService/*.csproj ./FOCS.NotificationService/
COPY FOCS/*.csproj ./FOCS/

# copy cả thư mục FOCS.NotificationService vào container
COPY FOCS.NotificationService /app/FOCS.NotificationService

# Restore dependencies for API project
RUN dotnet restore ./FOCS/FOCS.csproj

# Copy the full source
COPY . .

# Build and publish
WORKDIR /app/FOCS
RUN dotnet publish -c Release -o /out /p:UseAppHost=false

# Stage 2: Runtime
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /out .

ENTRYPOINT ["dotnet", "FOCS.dll"]
