version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on: 
      - redis
      - sqlserver
      - rabbitmq
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=SEP490FOCS;User Id=sa;Password=Hxs03122003@@;Encrypt=False;TrustServerCertificate=True;
      - Redis__ConnectionString=redis:6379
      - RabbitMQ__HostName=rabbitmq
      - ASPNETCORE_ENVIRONMENT=Production
    restart: always

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Hxs03122003@@"
      ACCEPT_EULA: "Y"
    restart: always

  redis: 
    image: redis:7
    container_name: redis
    ports: 
      - "6379:6379"
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672" 
    restart: always
