# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy only necessary files first to leverage Docker cache
COPY FOCS.sln ./
COPY FOCS/FOCS.csproj ./FOCS/

# Restore packages
RUN dotnet restore FOCS.sln

# Copy the rest of the source code
COPY . .

# Build the solution
RUN dotnet build FOCS.sln -c Release -o /app/build

# Publish the main API project
RUN dotnet publish ./FOCS/FOCS.csproj -c Release -o /app/publish /p:UseAppHost=false

# Runtime stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "FOCS.dll"]
