FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

# COPY toàn bộ mã nguồn (bao gồm cả các project con)
COPY . .

# restore solution
RUN dotnet restore FOCS.sln

# build & publish
RUN dotnet publish FOCS/FOCS.csproj -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "FOCS.dll"]
