name: CI/CD Deploy .NET API

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: self-hosted  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.407'

      - name: Restore dependencies
        run: dotnet restore FOCS.sln
        working-directory: ./SEP490-FOCS

      - name: Build project
        run: dotnet build FOCS.sln --configuration Release --no-restore
        working-directory: ./SEP490-FOCS

      - name: Publish FOCS project
        run: dotnet publish FOCS/FOCS.csproj --configuration Release --output ./publish/FOCS --no-build
        working-directory: ./SEP490-FOCS

      - name: Publish NotificationService project
        run: dotnet publish FOCS.NotificationService/FOCS.NotificationService.csproj --configuration Release --output ./publish/NotificationService --no-build
        working-directory: ./SEP490-FOCS


      - name: List files in SEP490-FOCS (debug)
        run: ls -l
        working-directory: ./SEP490-FOCS

      - name: Rename Dockerfile.txt to Dockerfile
        run: mv Dockerfile.txt Dockerfile
        working-directory: ./SEP490-FOCS

      - name: Deploy - restart container
        run: |
          docker stop focs-api || true
          docker rm focs-api || true
          docker build -t focs-api -f Dockerfile .
          docker run -d -p 5000:8080 --name focs-api focs-api
        working-directory: ./SEP490-FOCS
