name: CI/CD Deploy .NET API

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: self-hosted  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.407'

      - name: Restore dependencies
        run: dotnet restore FOCS.sln
        working-directory: ./SEP490-FOCS

      - name: Build project
        run: dotnet build FOCS.sln --configuration Release --no-restore
        working-directory: ./SEP490-FOCS

      - name: Publish project
        run: dotnet publish FOCS/FOCS.csproj --configuration Release --output ./publish --no-build
        working-directory: ./SEP490-FOCS

      - name: List files in current directory
        run: ls -l
        working-directory: ./SEP490-FOCS

      - name: Rename Dockerfile
        run: mv Dockerfile.txt Dockerfile

      - name: Deploy - restart container
        run: |
          docker stop focs-api || true
          docker rm focs-api || true
          mv Dockerfile.txt Dockerfile
          docker build -t focs-api .
          docker run -d -p 5000:8080 --name focs-api focs-api


