name: CI/CD Deploy .NET API

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted  
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.407'

      - name: Restore dependencies
        run: dotnet restore FOCS.sln
        working-directory: ./SEP490-FOCS

      - name: Build project
        run: dotnet build FOCS.sln --configuration Release --no-restore
        working-directory: ./SEP490-FOCS

      - name: Publish project
        run: dotnet publish FOCS/FOCS.csproj --configuration Release --output ./publish --no-build
        working-directory: ./SEP490-FOCS

      - name: Rename Dockerfile.txt to Dockerfile
        run: mv Dockerfile.txt Dockerfile
        working-directory: ./SEP490-FOCS

      - name: Deploy - restart container
        run: |
          docker compose -f docker-compose.yml down
          docker compose -f docker-compose.yml up -d --build
        working-directory: ./SEP490-FOCS
        env:
          TwilioSettings__AccountSid: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TwilioSettings__AuthToken: ${{ secrets.TWILIO_AUTH_TOKEN }}
          TwilioSettings__FromPhoneNumber: ${{ secrets.TWILIO_FROM_NUMBER }}
          FIREBASE_CREDENTIAL: ${{ secrets.FIREBASE_CREDENTIAL }}

          working-directory: ./SEP490-FOCS
