name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy source code to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: "/FOCS-BE---Cafeteria-Ordering-System/SEP490-FOCS/FOCS"

      - name: SSH deploy commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Current directory:"
            pwd

            echo "List files:"
            ls -la /FOCS-BE---Cafeteria-Ordering-System

            cd /FOCS-BE---Cafeteria-Ordering-System || exit 1

            echo "Stop containers if any"
            docker compose down || docker-compose down || echo "No containers to stop"

            echo "Start containers"
            docker compose up -d --build || docker-compose up -d --build
